version: "3.8"
services:
  postgres:
    image: postgres:13-alpine
    ports:
    - 45432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spark_server_dev
  server:
    image: spark-server:latest
    build:
      dockerfile: './Dockerfile'
      context: '.'
  # eth:
  #   image: trufflesuite/ganache-cli:v6.12.2
  #   command: '--accounts 10 --debug --db /app/data'
  #   ports:
  #   - '48545:8545'
  #   volumes:
  #   - ../data/spark_server/eth:/app/data
